name: fifteen_words_local
services:
  db:
    image: postgres:17
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: andy071811/fifteen_words:dockercompose
    init: true
    volumes:
      - .:/app
      - ./theme/static:/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./theme/static:/app/static
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: